export const PHONES_FETCH_START = 'PHONES_FETCH_START';
export const PHONES_FETCH_SUCCESS = 'PHONES_FETCH_SUCCESS';
export const PHONES_FETCH_FAILED = 'PHONES_FETCH_FAILED';

export const UPDATE_PHONES_ITEM_START = 'UPDATE_PHONES_ITEM_START';
export const UPDATE_PHONES_ITEM_FAILED = 'UPDATE_PHONES_ITEM_FAILED';
export const UPDATE_PHONES_ITEM_SUCCESS = 'UPDATE_PHONES_ITEM_SUCCESS';

export const ADD_PHONE_TO_CART = 'ADD_PHONE_TO_CART';
export const DELETE_PHONE_FROM_CART = 'DELETE_PHONE_FROM_CART';
export const CLEAR_CART = 'CLEAR_CART';

export const INCREASE_PHONE_QUANTITY = 'INCREASE_PHONE_QUANTITY';
export const DECREASE_PHONE_QUANTUTY = 'DECREASE_PHONE_QUANTUTY';
